name: fibra.lat

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js and cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
       
      # Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      # Install Playwright for e2e tests
      - name: Install Playwright
        run: npx playwright install --with-deps
      
      # Run format check
      - name: Format check
        run: npx nx format:check
      
      # Build calculator
      - name: Build
        run: npx nx build calculator --prod
      
  deploy:
    runs-on: ubuntu-latest
    needs: main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Build with Nx
        run: npx nx build calculator --prod
      
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel deploy --prod \
            --token=${VERCEL_TOKEN} \
            --scope=${VERCEL_ORG_ID} \
            --project=${VERCEL_PROJECT_ID} \
            --yes
