name: fibra.lat

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Start Nx Cloud CI Run for distributed task execution
      - name: Start Nx Cloud CI Run
        run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"
      
      # Setup Node.js and cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
       
      # Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      # Install Playwright for e2e tests
      - name: Install Playwright
        run: npx playwright install --with-deps
      
      # Set up SHAs for nx affected commands
      - name: Set up SHAs for affected commands
        uses: nrwl/nx-set-shas@v4

      # Run format check on affected files
      - name: Format check
        run: npx nx-cloud record -- npx nx format:check
      
      # Run lint on affected projects
      - name: Lint
        run: npx nx-cloud record -- npx nx affected -t lint --parallel=3

      # Run tests on affected projects
      - name: Test
        run: npx nx-cloud record -- npx nx affected -t test --parallel=3
        
      # Build affected projects
      - name: Build
        run: npx nx-cloud record -- npx nx affected -t build --parallel=3
      
  deploy:
    runs-on: ubuntu-latest
    needs: main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Build with Nx
        run: npx nx build calculator --prod
      
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel deploy --prod \
            --token=${VERCEL_TOKEN} \
            --scope=${VERCEL_ORG_ID} \
            --project=${VERCEL_PROJECT_ID} \
            --yes
